#!/bin/sh
sed -i -e 's/Stallman<\/h2>/Stallman・著<\/h2>\n<h2 class="tp-author">後藤洋 \/ 弓削光好・訳<\/h2>/' $1/OEBPS/top.html
sed -i -e 's/<itemref idref="toc" \/>//' -e 's/<itemref idref="rv-intro" \/>/<itemref idref="toc" \/>\n&/' $1/OEBPS/free_as_in_freedom_2.0_ja.opf
