#!/bin/sh
ruby -i -pe '$_.sub! /\*0</, "<"' $1/OEBPS/toc.html
ruby -i -pe '$_.sub! %r[Stallman</h2>], %Q[Stallman・著</h2>\n<h2 class="tp-author">後藤洋 / 弓削光好・訳</h2>]' $1/OEBPS/top.html
ruby -i -pe '$_.sub! %r[<itemref idref="toc" />], ""; $_.sub! %r[<itemref idref="rv-intro" />], %Q[<itemref idref="toc" />\n<itemref idref="rv-intro" />]' $1/OEBPS/free_as_in_freedom_2.0_ja.opf
ruby -i -pe '$_.sub! /\*0</, "<"' $1/OEBPS/free_as_in_freedom_2.0_ja.ncx
